version: "3.9"

services:
    db:
        image: postgres:16
        container_name: laravel_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: root
            POSTGRES_PASSWORD: secret
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5433:5432"

volumes:
    pgdata:
